- id: dd-zabbix
  type: group
  role: [dd-zabbix]
  requires: [deploy_start]
  required_for: [deploy_end]
  tasks: [hiera, globals, tools, logging, netconfig, hosts, deploy_start]
  parameters:
    strategy:
      type: one_by_one

- id: dd-zabbix-primary-controller
  type: puppet
  groups: [dd-zabbix]
  requires: [deploy_start]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/primary_controller.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360

- id: dd-zabbix-controller
  type: puppet
  groups: [dd-zabbix]
  required_for: [deploy_end]
  requires: [deploy_start, dd-zabbix-primary-controller]
  parameters:
    puppet_manifest: puppet/manifests/controller.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360

- id: dd-zabbix-config
  type: puppet
  groups: [dd-zabbix]
  required_for: [deploy_end]
  requires: [deploy_start, dd-zabbix-controller]
  parameters:
    puppet_manifest: puppet/manifests/zabbix_server_config.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360