#!/bin/bash
set -eux

ROOT="$(dirname `readlink -f $0`)"
RPM_REPO="${ROOT}"/repositories/centos/
DEB_REPO="${ROOT}"/repositories/ubuntu/
mkdir -p $RPM_REPO
mkdir -p $DEB_REPO

# Downloads needed RPM or DEB packages
function download {
    case "$1" in
        deb) REPO=$DEB_REPO;;
        rpm) REPO=$RPM_REPO;;
    esac
    shift

    while [ $# -gt 0 ]; do
        FILE=$(basename "$1")
        wget -qO - $1 > "$REPO/$FILE"
        shift
    done
}

download deb http://repo.zabbix.com/zabbix/2.4/ubuntu/pool/main/z/zabbix/zabbix-agent_2.4.4-1+trusty_amd64.deb \
             http://repo.zabbix.com/zabbix/2.4/ubuntu/pool/main/z/zabbix/zabbix-frontend-php_2.4.4-1+trusty_all.deb \
             http://repo.zabbix.com/zabbix/2.4/ubuntu/pool/main/z/zabbix/zabbix-server-mysql_2.4.4-1+trusty_amd64.deb \
             http://repo.zabbix.com/zabbix/2.4/ubuntu/pool/main/z/zabbix/zabbix-sender_2.4.4-1+trusty_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/p/php5/php5-mysql_5.5.9+dfsg-1ubuntu4.14_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/universe/n/net-snmp/libsnmp-perl_5.7.2~dfsg-8.1ubuntu3.1_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/universe/s/snmptt/snmptt_1.4-1_all.deb \
             http://archive.ubuntu.com/ubuntu/pool/universe/libs/libsmi/smistrip_0.4.8+dfsg2-8ubuntu2_all.deb \
             http://archive.ubuntu.com/ubuntu/pool/multiverse/s/snmp-mibs-downloader/snmp-mibs-downloader_1.1_all.deb \
             http://archive.ubuntu.com/ubuntu/pool/universe/i/iptstate/iptstate_2.2.5-1_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/d/dbconfig-common/dbconfig-common_1.8.47+nmu1_all.deb \
             http://archive.ubuntu.com/ubuntu/pool/universe/f/fping/fping_3.8-1_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/liba/libaio/libaio1_0.3.109-4_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/libc/libconfig-inifiles-perl/libconfig-inifiles-perl_2.82-1_all.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/libd/libdbd-mysql-perl/libdbd-mysql-perl_4.025-1_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/libd/libdbi-perl/libdbi-perl_1.630-1_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/libh/libhtml-template-perl/libhtml-template-perl_2.95-1_all.deb \
             http://archive.ubuntu.com/ubuntu/pool/universe/libi/libiksemel/libiksemel3_1.2-4.2_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/libl/liblist-moreutils-perl/liblist-moreutils-perl_0.33-1build3_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/libt/libtool/libltdl7_2.4.2-1.7ubuntu1_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-5.5/libmysqlclient18_5.5.46-0ubuntu0.14.04.2_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/u/unixodbc/libodbc1_2.2.14p2-5ubuntu5_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/o/openipmi/libopenipmi0_2.0.18-0ubuntu7.1_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/p/perl/libperl5.18_5.18.2-2ubuntu1_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/l/lm-sensors/libsensors4_3.3.4-2ubuntu1_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/n/net-snmp/libsnmp-base_5.7.2~dfsg-8.1ubuntu3.1_all.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/n/net-snmp/libsnmp30_5.7.2~dfsg-8.1ubuntu3.1_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/universe/libs/libssh2/libssh2-1_1.4.3-2_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/libt/libterm-readkey-perl/libterm-readkey-perl_2.31-1_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-5.5/mysql-client_5.5.46-0ubuntu0.14.04.2_all.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-5.5/mysql-client-5.5_5.5.46-0ubuntu0.14.04.2_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-5.5/mysql-client-core-5.5_5.5.46-0ubuntu0.14.04.2_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-5.5/mysql-common_5.5.46-0ubuntu0.14.04.2_all.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-5.5/mysql-server_5.5.46-0ubuntu0.14.04.2_all.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-5.5/mysql-server-5.5_5.5.46-0ubuntu0.14.04.2_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-5.5/mysql-server-core-5.5_5.5.46-0ubuntu0.14.04.2_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/n/net-snmp/snmpd_5.7.2~dfsg-8.1ubuntu3.1_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/a/apache2/apache2_2.4.7-1ubuntu4.8_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/a/apache2/apache2-bin_2.4.7-1ubuntu4.8_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/a/apache2/apache2-data_2.4.7-1ubuntu4.8_all.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/f/fontconfig/fontconfig-config_2.11.0-0ubuntu4.1_all.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/f/fonts-dejavu/fonts-dejavu-core_2.34-1ubuntu1_all.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/p/php5/libapache2-mod-php5_5.5.9+dfsg-1ubuntu4.14_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/a/apr/libapr1_1.5.0-1_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/a/apr-util/libaprutil1_1.5.3-1_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/a/apr-util/libaprutil1-dbd-sqlite3_1.5.3-1_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/a/apr-util/libaprutil1-ldap_1.5.3-1_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/f/fontconfig/libfontconfig1_2.11.0-0ubuntu4.1_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/libg/libgd2/libgd3_2.1.0-3_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/j/jbigkit/libjbig0_2.0-2ubuntu4.1_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/libj/libjpeg-turbo/libjpeg-turbo8_1.3.0-0ubuntu2_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/libj/libjpeg8-empty/libjpeg8_8c-2ubuntu8_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/t/tiff/libtiff5_4.0.3-7ubuntu0.3_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/libv/libvpx/libvpx1_1.3.0-2_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/libx/libxpm/libxpm4_3.5.10-1_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/p/php5/php5_5.5.9+dfsg-1ubuntu4.14_all.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/p/php5/php5-cli_5.5.9+dfsg-1ubuntu4.14_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/p/php5/php5-common_5.5.9+dfsg-1ubuntu4.14_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/p/php5/php5-gd_5.5.9+dfsg-1ubuntu4.14_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/p/php-json/php5-json_1.3.2-2build1_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/p/php5/php5-mysql_5.5.9+dfsg-1ubuntu4.14_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/p/php5/php5-readline_5.5.9+dfsg-1ubuntu4.14_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/f/fonts-dejavu/ttf-dejavu-core_2.34-1ubuntu1_all.deb


download rpm http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-agent-2.4.4-1.el6.x86_64.rpm \
             http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-server-2.4.4-1.el6.x86_64.rpm \
             http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-server-mysql-2.4.4-1.el6.x86_64.rpm \
             http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-web-2.4.4-1.el6.noarch.rpm \
             http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-web-mysql-2.4.4-1.el6.noarch.rpm \
             http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-sender-2.4.4-1.el6.x86_64.rpm \
             http://mirror.centos.org/centos/6/os/x86_64/Packages/iptstate-2.2.2-4.el6.x86_64.rpm

# dbconfig-common           http://archive.ubuntu.com/ubuntu/pool/main/d/dbconfig-common/dbconfig-common_1.8.47+nmu1_all.deb
# fping                     http://archive.ubuntu.com/ubuntu/pool/universe/f/fping/fping_3.8-1_amd64.deb
# libaio1                   http://archive.ubuntu.com/ubuntu/pool/main/liba/libaio/libaio1_0.3.109-4_amd64.deb
# libconfig-inifiles-perl   http://archive.ubuntu.com/ubuntu/pool/main/libc/libconfig-inifiles-perl/libconfig-inifiles-perl_2.82-1_all.deb
# libdbd-mysql-perl         http://archive.ubuntu.com/ubuntu/pool/main/libd/libdbd-mysql-perl/libdbd-mysql-perl_4.025-1_amd64.deb
# libdbi-perl               http://archive.ubuntu.com/ubuntu/pool/main/libd/libdbi-perl/libdbi-perl_1.630-1_amd64.deb
# libhtml-template-perl     http://archive.ubuntu.com/ubuntu/pool/main/libh/libhtml-template-perl/libhtml-template-perl_2.95-1_all.deb
# libiksemel3               http://archive.ubuntu.com/ubuntu/pool/universe/libi/libiksemel/libiksemel3_1.2-4.2_amd64.deb
# liblist-moreutils-perl    http://archive.ubuntu.com/ubuntu/pool/main/libl/liblist-moreutils-perl/liblist-moreutils-perl_0.33-1build3_amd64.deb
# libltdl7                  http://archive.ubuntu.com/ubuntu/pool/main/libt/libtool/libltdl7_2.4.2-1.7ubuntu1_amd64.deb
# libmysqlclient18          http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-5.5/libmysqlclient18_5.5.46-0ubuntu0.14.04.2_amd64.deb
# libodbc1                  http://archive.ubuntu.com/ubuntu/pool/main/u/unixodbc/libodbc1_2.2.14p2-5ubuntu5_amd64.deb
# libopenipmi0              http://archive.ubuntu.com/ubuntu/pool/main/o/openipmi/libopenipmi0_2.0.18-0ubuntu7.1_amd64.deb
# libperl5.18               http://archive.ubuntu.com/ubuntu/pool/main/p/perl/libperl5.18_5.18.2-2ubuntu1_amd64.deb
# libsensors4               http://archive.ubuntu.com/ubuntu/pool/main/l/lm-sensors/libsensors4_3.3.4-2ubuntu1_amd64.deb
# libsnmp-base              http://archive.ubuntu.com/ubuntu/pool/main/n/net-snmp/libsnmp-base_5.7.2~dfsg-8.1ubuntu3.1_all.deb
# libsnmp30                 http://archive.ubuntu.com/ubuntu/pool/main/n/net-snmp/libsnmp30_5.7.2~dfsg-8.1ubuntu3.1_amd64.deb
# libssh2-1                 http://archive.ubuntu.com/ubuntu/pool/universe/libs/libssh2/libssh2-1_1.4.3-2_amd64.deb
# libterm-readkey-perl      http://archive.ubuntu.com/ubuntu/pool/main/libt/libterm-readkey-perl/libterm-readkey-perl_2.31-1_amd64.deb
# mysql-client              http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-5.5/mysql-client_5.5.46-0ubuntu0.14.04.2_all.deb
# mysql-client-5.5          http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-5.5/mysql-client-5.5_5.5.46-0ubuntu0.14.04.2_amd64.deb
# mysql-client-core-5.5     http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-5.5/mysql-client-core-5.5_5.5.46-0ubuntu0.14.04.2_amd64.deb
# mysql-common              http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-5.5/mysql-common_5.5.46-0ubuntu0.14.04.2_all.deb
# mysql-server              http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-5.5/mysql-server_5.5.46-0ubuntu0.14.04.2_all.deb
# mysql-server-5.5          http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-5.5/mysql-server-5.5_5.5.46-0ubuntu0.14.04.2_amd64.deb
# mysql-server-core-5.5     http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-5.5/mysql-server-core-5.5_5.5.46-0ubuntu0.14.04.2_amd64.deb
# snmpd                     http://archive.ubuntu.com/ubuntu/pool/main/n/net-snmp/snmpd_5.7.2~dfsg-8.1ubuntu3.1_amd64.deb

# apache2                   http://archive.ubuntu.com/ubuntu/pool/main/a/apache2/apache2_2.4.7-1ubuntu4.8_amd64.deb
# apache2-bin               http://archive.ubuntu.com/ubuntu/pool/main/a/apache2/apache2-bin_2.4.7-1ubuntu4.8_amd64.deb
# apache2-data              http://archive.ubuntu.com/ubuntu/pool/main/a/apache2/apache2-data_2.4.7-1ubuntu4.8_all.deb
# fontconfig-config         http://archive.ubuntu.com/ubuntu/pool/main/f/fontconfig/fontconfig-config_2.11.0-0ubuntu4.1_all.deb         
# fonts-dejavu-core         http://archive.ubuntu.com/ubuntu/pool/main/f/fonts-dejavu/fonts-dejavu-core_2.34-1ubuntu1_all.deb
# libapache2-mod-php5       http://archive.ubuntu.com/ubuntu/pool/main/p/php5/libapache2-mod-php5_5.5.9+dfsg-1ubuntu4.14_amd64.deb
# libapr1                   http://archive.ubuntu.com/ubuntu/pool/main/a/apr/libapr1_1.5.0-1_amd64.deb
# libaprutil1               http://archive.ubuntu.com/ubuntu/pool/main/a/apr-util/libaprutil1_1.5.3-1_amd64.deb
# libaprutil1-dbd-sqlite3   http://archive.ubuntu.com/ubuntu/pool/main/a/apr-util/libaprutil1-dbd-sqlite3_1.5.3-1_amd64.deb
# libaprutil1-ldap          http://archive.ubuntu.com/ubuntu/pool/main/a/apr-util/libaprutil1-ldap_1.5.3-1_amd64.deb
# libfontconfig1            http://archive.ubuntu.com/ubuntu/pool/main/f/fontconfig/libfontconfig1_2.11.0-0ubuntu4.1_amd64.deb
# libgd3                    http://archive.ubuntu.com/ubuntu/pool/main/libg/libgd2/libgd3_2.1.0-3_amd64.deb
# libjbig0                  http://archive.ubuntu.com/ubuntu/pool/main/j/jbigkit/libjbig0_2.0-2ubuntu4.1_amd64.deb
# libjpeg-turbo8            http://archive.ubuntu.com/ubuntu/pool/main/libj/libjpeg-turbo/libjpeg-turbo8_1.3.0-0ubuntu2_amd64.deb
# libjpeg8                  http://archive.ubuntu.com/ubuntu/pool/main/libj/libjpeg8-empty/libjpeg8_8c-2ubuntu8_amd64.deb
# libtiff5                  http://archive.ubuntu.com/ubuntu/pool/main/t/tiff/libtiff5_4.0.3-7ubuntu0.3_amd64.deb
# libvpx1                   http://archive.ubuntu.com/ubuntu/pool/main/libv/libvpx/libvpx1_1.3.0-2_amd64.deb
# libxpm4                   http://archive.ubuntu.com/ubuntu/pool/main/libx/libxpm/libxpm4_3.5.10-1_amd64.deb
# php5                      http://archive.ubuntu.com/ubuntu/pool/main/p/php5/php5_5.5.9+dfsg-1ubuntu4.14_all.deb
# php5-cli                  http://archive.ubuntu.com/ubuntu/pool/main/p/php5/php5-cli_5.5.9+dfsg-1ubuntu4.14_amd64.deb
# php5-common               http://archive.ubuntu.com/ubuntu/pool/main/p/php5/php5-common_5.5.9+dfsg-1ubuntu4.14_amd64.deb
# php5-gd                   http://archive.ubuntu.com/ubuntu/pool/main/p/php5/php5-gd_5.5.9+dfsg-1ubuntu4.14_amd64.deb
# php5-json                 http://archive.ubuntu.com/ubuntu/pool/main/p/php-json/php5-json_1.3.2-2build1_amd64.deb
# php5-mysql                http://archive.ubuntu.com/ubuntu/pool/main/p/php5/php5-mysql_5.5.9+dfsg-1ubuntu4.14_amd64.deb
# php5-readline             http://archive.ubuntu.com/ubuntu/pool/main/p/php5/php5-readline_5.5.9+dfsg-1ubuntu4.14_amd64.deb
# ttf-dejavu-core           http://archive.ubuntu.com/ubuntu/pool/main/f/fonts-dejavu/ttf-dejavu-core_2.34-1ubuntu1_all.deb

# snmptt
# libsnmp-perl
# zabbix-server-mysql